import React from "react";
import { ActionManager } from "../actions/manager";
import { NonDeletedExcalidrawElement } from "../element/types";
import { Language } from "../i18n";
import { AppProps, AppState, ExcalidrawProps } from "../types";
import "./LayerUI.scss";
interface LayerUIProps {
    onHomeButtonClick?: () => void;
    actionManager: ActionManager;
    appState: AppState;
    canvas: HTMLCanvasElement | null;
    setAppState: React.Component<any, AppState>["setState"];
    elements: readonly NonDeletedExcalidrawElement[];
    onCollabButtonClick?: () => void;
    onLockToggle: () => void;
    onInsertElements: (elements: readonly NonDeletedExcalidrawElement[]) => void;
    zenModeEnabled: boolean;
    showExitZenModeBtn: boolean;
    showThemeBtn: boolean;
    toggleZenMode: () => void;
    langCode: Language["code"];
    isCollaborating: boolean;
    onExportToBackend?: (exportedElements: readonly NonDeletedExcalidrawElement[], appState: AppState, canvas: HTMLCanvasElement | null) => void;
    renderTopRight?: (isMobile: boolean) => JSX.Element;
    renderCustomFooter?: (isMobile: boolean) => JSX.Element;
    viewModeEnabled: boolean;
    libraryReturnUrl: ExcalidrawProps["libraryReturnUrl"];
    UIOptions: AppProps["UIOptions"];
}
declare const _default: React.MemoExoticComponent<({ onHomeButtonClick, actionManager, appState, setAppState, canvas, elements, onCollabButtonClick, onLockToggle, onInsertElements, zenModeEnabled, showExitZenModeBtn, showThemeBtn, toggleZenMode, isCollaborating, onExportToBackend, renderCustomFooter, renderTopRight, viewModeEnabled, libraryReturnUrl, UIOptions, }: LayerUIProps) => JSX.Element>;
export default _default;
